language: python
python:
- '2.7'
- '3.4'
- '3.5'
install:
- pip install -r requirements.txt -r requirements-dev.txt
before_script:
- flake8 .
script:
- nosetests --with-coverage
after_success:
- coveralls
deploy:
  provider: heroku
  buildpack: python
  api_key: $heroku_api_key
  app:
    master: sumapi-staging
    develop: sumapi-develop
env:
  global:
  - secure: MhriwGoAsr8dc4z8yiaGPFwIvzXTiYMYtZUncwC4wq8t1W3cE6aUapEQ8irQ3gN71TK/JmSRDKl4rfKo4tXE1WwT/LAo0Z+qm/PtRVca7Me5rszRTQ0IIIHNCBIAoEdUO+bOSyi6h/+aAoQoK0uPJ7FfwC5QKzV3XAfTuUn+GLLm6pvrum5uuAgGJEPfMRSAX2ZdPO+L41xXi28uY37wjgRkLfzh/SKuP6kjauifJ9uGVyQf8raq+xouJ7Yf9ZiGM+iV7YivTyzpt8pYPNkMOIlozEa7FepEXLsfFEAWBnvI30MV0X2YU5i6ZygJz1yXqIjP/7eFji6KnHGkSZWROlzWNDaGpR0Cn9H2JhG0TswkEuXDwKJvFv+z61GOIPuyExv5gGKh68yf120cMOOgL11EU9HXhth9L1wp35a4ukuusSnsSBOJzya5KobpGY39na/7ucZ7j3MDUk0VTo1oqeMAz1bPB5o8gFhnBknJkSD7+3KmZiQqomxXUMj0BVTRqceUSSzpi5gNX3cRdVFN8mh6M6CCSjb1PipMOtGe7VarFGN/SZy2vRNj6QuuU4Z0+RowtMHe41FpQNTkfivtHRyP4LkQ54hxKtEMSfSMni7TR0TzPAn/kJ6XdDpefXfohcNgJkZrpCsivXCkMrQktiJaQTmBFc4wVPLRPINnD6U=
